# title: Prince Javier # your name (or website title) here
# # logo: "/images/prince.png" # your photo (or logo) here
# description: > # your text below (remove <br> elements if you don't need line breaks)
#   I am an engineer, data scientist, and cofounder of Bridge360, a tech startup based in the Philippines that provides tech solutions to businesses. Bridge 360 also holds tech, social, and environmental meetups and workshops. 
#   <br><br>Aside from our startup, I work as a data scientist at Mynt, a top FinTech company in the Philippines. Before venturing into data science, my line of work was in engineering design, project management, and financial modeling. 
#   <br><br><a href="https://www.linkedin.com/in/princejavier/">View My LinkedIn Profile</a>
  
# theme: jekyll-theme-minimal
google_analytics: UA-150364500-1 # your Google Analytics tracking ID here
